Type: aws/rds-aurora
Stage: 01-test
Persist: true
IngressPoint: false

Configuration:
  Features:
    Type: Pipeline::Features
    Properties:
      Features:
        Datadog : enabled

  MyDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: "aurora-mysql"
      EngineVersion: "5.7.mysql_aurora.2.08.3"
      EngineMode: "serverless"
      PerformanceInsightsEnabled: "true"
    Security:
      # Allow access by test-instance
      - Source: test-instance.SecurityGroup
        Allow: ALL:*

  MyClusterParams:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Family: "aurora-mysql5.7"
      Parameters:
        character_set_database: "utf32"
        server_audit_logging: "on"
        server_audit_events: "CONNECT,QUERY,QUERY_DCL,QUERY_DDL,QUERY_DML,TABLE"
        