# RHEL6 autoscale component
# - Runs HTTP server with /index.html /health pages
---
Type: aws/autoscale
Stage: 01-test
Persist: true

Configuration:
  # Bake instance configuration
  Features:
    Type: Pipeline::Features
    Properties:
      Features:
        CodeDeploy: enabled
        Datadog: enabled
        Qualys:
          Enabled: true
          Recipients: ["csi@qantas.com.au"]
        IPS:
          Enabled: true
          Behaviour: detective

  BakeInstance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          Deploy: [ "Configure" , "Install" ]
        Configure:
          commands:
            bootstrap:
              command: bash bootstrap.sh
              cwd: /root/payload
        Install:
          commands:
            01-copy-files:
              command: mkdir /root/app && cp -r /root/payload/* /root/app
    CreationPolicy:
      ResourceSignal:
        Timeout: PT45M
    Properties:
      ImageId: "@amazon-latest"
      InstanceType: m4.large

  # Autoscaling Group configuration
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Security:
      - Source: alb-codedeploy.SecurityGroup
        Allow: TCP:80
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    Properties:
      MinSize: 1
      MaxSize: 1
      HealthCheckGracePeriod: 900
      TargetGroupARNs:
        - "@alb-codedeploy.GroupAArn"

  # Launch Configuration configuration
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          Deploy: [ "Install" ]
        Install:
          commands:
            01-run-schedule:
              command: 'bash /root/app/schedule.sh'
    Properties:
      InstanceType: m4.large
      SpotPrice: "@ondemand"

Environments:
  DEV:
    Configuration:
      BakeInstance:
        Properties:
          KeyName: pipeline
      LaunchConfiguration:
        Properties:
          KeyName: pipeline