# SQL server EE with option group
---
Type: aws/rds-oracle
Stage: 01-test
Persist: true

Configuration:
  Features:
    Type: Pipeline::Features
    Properties:
      Features:
        Datadog : enabled

  Database:
    Type: AWS::RDS::DBInstance
    Security:
      # Allow access to database from my-instance
      - Source: test-instance.SecurityGroup
        Allow: ALL:*
    Properties:
      AllocatedStorage: 100
      EnablePerformanceInsights: true
      Engine: oracle-ee
      EngineVersion: 19.0.0.0.ru-2022-01.rur-2022-01.r1
      DBName: testdb
      DBInstanceClass: db.m5.large
      MasterUserPassword: '@app.pipeline_oracle_password'
      MasterUsername: root
      MultiAZ: false
      StorageType: io1
      Iops: 1000
      EnableCloudwatchLogExports:
        - alert
        - audit
        - listener
        - trace

  # Subscription filters for each audit log type

  SubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: "@kinesis.LogCollectorArn"

