# Postgresql DB with custom parameter group
---
Type: aws/rds-postgresql
Stage: 01-test
Persist: true

Configuration:
  Database:
    Type: AWS::RDS::DBInstance
    Security:
      # Allow access to database from my-instance
      - Source: test-instance.SecurityGroup
        Allow: ALL:*
      - Source: postgresql.SecurityGroup
        Allow: ALL:*
    Properties:
      AllocatedStorage: 100
      DBName: pgdb
      DBInstanceClass: db.m5.large
      EngineVersion: 14.8
      EnablePerformanceInsights: true
      MasterUserPassword: '@app.pipeline_postgresql_password'
      MasterUsername: root
      MultiAZ: false
      StorageType: io1
      Iops: 1000
  PgReplica1:
    Type: AWS::RDS::DBInstance
    Security:
      # Allow access to database from pricing
      - Source: postgresql.SecurityGroup
        Allow: ALL:*
    Properties:
      AllocatedStorage: 100
      DBInstanceClass: db.m5.large
      SourceDBInstanceIdentifier: Database
      StorageType: io1
      Iops: 1000
  PGParams:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Family: postgres14
      Parameters:
        log_min_duration_statement: 1000

