# SQL server EE with option group
---
Type: aws/rds-sqlserver
Stage: 01-test
Persist: true

Configuration:
  Database:
    Type: AWS::RDS::DBInstance
    Security:
      # Allow access to database from my-instance
      - Source: test-instance.SecurityGroup
        Allow: ALL:*
    Properties:
      AllocatedStorage: 200
      DBInstanceClass: db.m5.large
      MultiAZ: false
      EnablePerformanceInsights: true
      Timezone: "E. Australia Standard Time"
      StorageType: io1
      Iops: 2000
