---
Type: aws/lambda
Stage: "01"
Persist: false

Configuration:
  LoadFuction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: load.handler
      Runtime: python3.9
      Timeout: 60
      MemorySize: 256
      Code: package.zip

  NotifySNS:
    Type: AWS::SNS::Subscription
    Properties:
      Pipeline::EventTarget: '@deployed'
      TopicArn: "@srv-sns.DataLoaderArn"
      DeliveryPolicy:
        healthyRetryPolicy:
          numRetries: 20
          minDelayTarget: 10
          maxDelayTarget: 30
          numMinDelayRetries: 3
          numMaxDelayRetries: 17
          numNoDelayRetries: 0