---
Type: aws/lambda
Stage: "01"
Persist: false

Configuration:
  LoadFuction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: load.handler
      Runtime: python3.9
      Timeout: 60
      MemorySize: 256
      Code: package.zip

Actions:
  PreRelease:
    - Action: InvokeLambda
      Stage: "00"
      Parameters:
        Target: "@deployed"