---
Type: aws/lambda
Stage: "01"
Persist: false

Configuration:
  StreamProcessor:
    Type: AWS::Lambda::Function
    Properties:
      Handler: load.handler
      Runtime: python3.9
      Timeout: 60
      MemorySize: 256
      Code: package.zip

  StreamMapper:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      Pipeline::EventTarget: '@released'
      EventSourceArn: "@srv-dynamo.MyTableStreamArn"
      StartingPosition: LATEST