# Windows 2019 single instance used to test Windows 2012 scripts
# Note: other components should have security rules allowing access to this component.
# This component will test:
# - volume-win2012 attach/detach via AWS CLI
# - attach_volume and detach_volume scripts
# - kms_decrypt script
# - attach_eni and detach_eni scripts
---
Type: aws/instance
Stage: 01-test
Persist: false
IngressPoint: true

Configuration:
  Features:
    Type: Pipeline::Features
    Properties:
      Features:
        CodeDeploy: disabled
        Datadog: enabled
        Qualys:
          Enabled: false
          Recipients: ["csi@qantas.com.au"]
        CustomTags:
          Enabled: true
          Tags:
            ProjectCode: c031-01

  Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          commands:
            01-test-context-include:
              command: 'powershell.exe -File c:\\windows\\temp\\payload\\context-include.ps1'
            01-test-context-include-noprofile:
              command: 'powershell.exe -File c:\\windows\\temp\\payload\\context-include.ps1 -noprofile'
    Properties:
      AvailabilityZone: "@a"
      ImageId: "@win2019-latest"
      InstanceType: m4.large
Environments:
  DEV:
    Configuration:
      Instance:
        Properties:
          KeyName: pipeline
